name: Deploy PR
description: Deploy pull requests as static sites to Surge.sh
author: "Koj <https://github.com/koj.co>"
inputs:
  token:
    required: false
    description: GitHub token
  prefix:
    required: false
    description: Prefix in deployment URL
  robotsTxtPath:
    required: false
    description: Path to create robots.txt in
  distDir:
    required: true
    description: Directory to deploy
runs:
  using: node12
  pre: "npm install --global surge"
  main: dist/index.js
