name: Test CI
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test action
    runs-on: ubuntu-18.04
    if: "contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          prefix: deploy-pr-example
          distDir: .
